### ISSUE TITLE
Support Encrypted File 

### ISSUE THREAD

**Issue by tabuna** [mops1k/unoserver-client#1]
I have an encrypted file (password is known), and I would like to provide the password before initiating the conversion process. Is it possible to implement functionality that allows for passing the file's password to the system prior to conversion?

**Comment by mops1k** [comment]
As i know, unoserver does not support encrypted files. If it does and you know options to pass, i can implement it. Or you can write new wrapper [example](https://github.com/mops1k/unoserver-client/blob/main/src/Wrapper/Local.php) and create PR.

**Comment by tabuna** [comment]
Thank you for your response! 

Indeed, **unoserver** doesn’t have the capability to remove passwords—I created this thread before knowing that. I appreciate your repository, but unfortunately, it didn’t fit my needs. 

In the end, I solved the issue using **msoffcrypto-tool** by creating [lumos](https://github.com/esplora/lumos).
